name: Format Check

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install autopep8
        run: |
          python -m pip install --upgrade pip
          pip install autopep8

      - name: Run autopep8 Check
        run: autopep8 --diff --recursive .
